map $request_method $arc_xhttp_method {
    default $request_method;
    OPTIONS POST;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name ru.arccnet.space _;

    root /var/www/ru-arccnet;
    index index.html;

    location /api-test {
        proxy_method $arc_xhttp_method;
        proxy_pass http://87.121.47.203;
        proxy_http_version 1.1;
        proxy_set_header Host cdn-de.arccnet.space;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 127.0.0.1:8444 ssl;
    server_name ru.arccnet.space;

    ssl_certificate /etc/letsencrypt/live/ru.arccnet.space/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ru.arccnet.space/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/ru-arccnet;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
