map $ssl_preread_server_name $sni_backend {
    sub.arccnet.space      127.0.0.1:2053;
    panel.arccnet.space    127.0.0.1:2053;
    arccnet.space          127.0.0.1:2053;
    default                127.0.0.1:4430;
}

server {
    listen 443;
    listen [::]:443;
    ssl_preread on;
    proxy_pass $sni_backend;
    proxy_connect_timeout 5s;
    proxy_timeout 300s;
}
