<script>
  import ArcIcon from '../../components/ArcIcon.svelte'
  export let data
  export let diagnostics = {}
  export let diagnosticNode = ''
  export let onDiagnostic
  $: nodes = data?.remnawave?.nodes || []
</script>
<section class="page"><header><div><span>ИНФРАСТРУКТУРА</span><h2>Ноды ArcVPN</h2><p>Подключение, нагрузка, трафик и глубокая диагностика каждого узла.</p></div><button><b>＋</b>Подключить ноду</button></header>
  <div class="toolbar"><button class="active">Все <i>{nodes.length}</i></button><button>Онлайн <i>{nodes.filter(n=>n.connected).length}</i></button><button>Проблемы <i>{nodes.filter(n=>!n.connected).length}</i></button></div>
  <div class="nodes">{#each nodes as node}<article class:off={!node.connected}><header><div class="flag">{node.country_code || '—'}</div><div><b>{node.name}</b><small>{node.address}:{node.port}</small></div><em>{node.connected ? 'ONLINE' : 'OFFLINE'}</em></header><div class="stats"><span><small>ПОЛЬЗОВАТЕЛИ</small><b>{node.users_online || 0}</b></span><span><small>ТРАФИК</small><b>{node.traffic_used_gb || 0} ГБ</b></span><span><small>RAM</small><b>{node.memory_used_pct || 0}%</b></span><span><small>UPTIME</small><b>{Math.floor(Number(node.xray_uptime_seconds || 0)/3600)} ч</b></span></div><div class="inbounds">{#each node.inbounds || [] as inbound}<span>{String(inbound.network || inbound.type || '').toUpperCase()} <b>:{inbound.port}</b></span>{/each}</div>{#if diagnostics[node.uuid]}<p class:good={diagnostics[node.uuid].ok}>Последний тест: {diagnostics[node.uuid].ok ? 'пройден' : diagnostics[node.uuid].error}</p>{/if}<footer><button disabled={diagnosticNode===node.uuid} on:click={()=>onDiagnostic(node)}><ArcIcon name="pulse" size={16}/>{diagnosticNode===node.uuid ? 'Проверяем…' : 'Глубокий тест'}</button><button class="more">•••</button></footer></article>{/each}</div>
</section>
<style>.page{display:grid;gap:18px}.page>header{display:flex;align-items:flex-end;justify-content:space-between}.page>header span{color:#e99772;font-size:10px;font-weight:800;letter-spacing:.14em}.page h2{margin:8px 0 5px;font-size:30px}.page>header p{margin:0;color:#8d8687}.page>header button,.nodes footer button{display:flex;align-items:center;gap:8px;padding:12px 16px;border:1px solid #392f31;border-radius:14px;background:#1b1618;color:#eee7e6}.toolbar{display:flex;gap:7px}.toolbar button{padding:10px 14px;border:0;border-radius:13px;background:#171315;color:#857d7f}.toolbar button.active{background:#eaa082;color:#211617}.toolbar i{margin-left:5px;font-style:normal}.nodes{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.nodes>article{padding:21px;border:1px solid #302729;border-radius:24px;background:linear-gradient(150deg,#1c1719,#131113)}.nodes>article.off{opacity:.75;border-color:#583133}.nodes article>header{display:flex;align-items:center;gap:11px}.flag{display:grid;place-items:center;width:44px;height:44px;border-radius:15px;background:#2a2224;color:#eaa082;font-weight:800}.nodes article>header>div:nth-child(2){display:flex;flex:1;flex-direction:column}.nodes header small{color:#857d7f}.nodes em{padding:7px 10px;border-radius:12px;background:#173127;color:#75ddb0;font-size:9px;font-style:normal;font-weight:800}.off em{background:#352023;color:#ef8c80}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:20px 0}.stats span{padding:12px;border-radius:15px;background:#211b1d}.stats small,.stats b{display:block}.stats small{color:#786f71;font-size:8px}.stats b{margin-top:7px}.inbounds{display:flex;flex-wrap:wrap;gap:6px}.inbounds span{padding:7px 9px;border-radius:11px;background:#211b1d;color:#a39a9b;font-size:10px}.inbounds b{color:#eda487}.nodes article>p{color:#ed8b80}.nodes article>p.good{color:#75d8aa}.nodes footer{display:flex;gap:8px;margin-top:18px}.nodes footer button:first-child{flex:1;justify-content:center}.nodes footer .more{width:44px;padding:0;justify-content:center}@media(max-width:950px){.nodes{grid-template-columns:1fr}.stats{grid-template-columns:1fr 1fr}}</style>
