<script>
  import { manageAdminSubscription, fetchAdminUserDetail } from '../../lib/api.js'
  export let users=[]; export let onRefresh
  let filter='new';let selected=null;let days=30;let busy=false;let notice='';let detail=null;let detailLoading=false
  const rub=v=>`${new Intl.NumberFormat('ru-RU').format(Number(v||0))} ₽`
  $: visible=users.filter(u=>filter==='all'||(filter==='online'?Number(u.online_devices)>0:filter==='inactive'?!u.active:true)).sort((a,b)=>filter==='top'?Number(b.paid_rub)-Number(a.paid_rub):new Date(b.created_at)-new Date(a.created_at))
  const date=v=>v?new Date(String(v).replace(' ','T')+'Z').toLocaleString('ru-RU',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—'
  const bytes=v=>Number(v||0)>0?`${(Number(v)/1024**3).toFixed(1)} ГБ`:'0 ГБ'
  function daysLeft(value){return value?Math.ceil((new Date(String(value).replace(' ','T')+'Z')-Date.now())/86400000):0}
  async function open(user){if(selected===user.telegram_id){selected=null;detail=null;return}selected=user.telegram_id;detail=null;detailLoading=true;try{detail=await fetchAdminUserDetail(user.telegram_id)}catch(e){notice=`Не удалось открыть карточку: ${e.reason||e.message}`}finally{detailLoading=false}}
  async function act(user,action,payload={}){busy=true;notice='';try{await manageAdminSubscription(user.telegram_id,{action,...payload});notice='Изменение сохранено и попадёт в Remnawave ближайшим sync';await onRefresh()}catch(e){notice=`Ошибка: ${e.reason||e.message}`}finally{busy=false}}
</script>
<section class="page"><header><span>КЛИЕНТСКАЯ БАЗА</span><h2>Подписки пользователей</h2><p>Продлевайте, сокращайте, отключайте и перевыпускайте ссылки без терминала.</p></header>
  <nav>{#each [['new','Новые'],['top','Больше заплатили'],['online','Онлайн'],['inactive','Неактивные'],['all','Все']] as item}<button class:active={filter===item[0]} on:click={()=>filter=item[0]}>{item[1]}</button>{/each}</nav>
  {#if notice}<p class="notice">{notice}</p>{/if}
  <div class="list">{#each visible as user}<article class:opened={selected===user.telegram_id}><button class="summary" on:click={()=>open(user)}><div><b>{user.first_name||user.username||`ID ${user.telegram_id}`}</b><small>@{user.username||'без username'} · оплачено {rub(user.paid_rub)} · до {date(user.expires_at)}</small></div><span class:ok={user.active}>{user.active?(Number(user.online_devices)>0?'Онлайн':'Активен'):'Неактивен'}</span></button>
    {#if selected===user.telegram_id}<div class="drawer">
      {#if detailLoading}<p>Собираем подписки, платежи и устройства…</p>{:else if detail}
        <div class="facts"><span><small>СРОК</small><b>{daysLeft(detail.subscriptions?.[0]?.expires_at)} дней</b></span><span><small>ДЕЙСТВУЕТ ДО</small><b>{date(detail.subscriptions?.[0]?.expires_at)}</b></span><span><small>БАЛАНС</small><b>{rub(detail.user?.balance_rub)}</b></span><span><small>УСТРОЙСТВА</small><b>{(detail.devices||[]).filter(d=>d.active).length}/{detail.user?.device_limit||2}</b></span></div>
        <div class="columns"><section><header><b>Подписки</b><span>{detail.subscriptions?.length||0}</span></header>{#each detail.subscriptions||[] as sub}<article><div><b>{sub.custom_name||sub.tariff_name||`Подписка #${sub.id}`}</b><small>{sub.active?'Активна':'Завершена'} · до {date(sub.expires_at)} · трафик {bytes(sub.traffic_used)}</small></div><em>{sub.online_devices||0} онлайн</em></article>{/each}</section>
        <section><header><b>История оплат</b><span>{detail.payments?.length||0}</span></header>{#each detail.payments||[] as payment}<article><div><b>{Number(payment.amount_rub)>0?rub(payment.amount_rub):Number(payment.amount_usd)>0?`$${Number(payment.amount_usd).toFixed(2)}`:`${payment.amount_stars||0} Stars`}</b><small>{payment.tariff_name||payment.payment_type} · {date(payment.paid_at)}</small></div><em class:paid={['paid','succeeded'].includes(payment.status)}>{payment.status}</em></article>{/each}</section></div>
      {/if}
      <div class="actions"><label>Дней <input type="number" min="1" max="1095" bind:value={days}/></label><button disabled={busy} on:click={()=>act(user,'adjust_days',{days:Number(days)})}>Добавить</button><button disabled={busy} on:click={()=>act(user,'adjust_days',{days:-Number(days)})}>Убрать</button><button disabled={busy} on:click={()=>act(user,'activate_days',{days:Number(days)})}>Активировать от сегодня</button><button disabled={busy} on:click={()=>confirm('Старая ссылка и ссылки устройств перестанут работать. Перевыпустить?')&&act(user,'regenerate_url')}>Перевыпустить ссылки</button><button disabled={busy} class="danger" on:click={()=>confirm('Отключить подписку пользователя?')&&act(user,'disable')}>Отключить</button></div>
    </div>{/if}
  </article>{/each}</div>
</section>
<style>.page{display:grid;gap:18px;max-width:1180px}.page>header span{color:#80c9f4;font-size:10px;font-weight:900;letter-spacing:.15em}.page h2{margin:8px 0 6px;font-size:30px}.page p{margin:0;color:#7890a5}.page>nav{display:flex;gap:7px}.page>nav button{padding:10px 14px;border:0;border-radius:12px;background:#101b29;color:#7890a5}.page>nav button.active{background:#9bd9ff;color:#07111d}.list{display:grid;gap:7px}.list>article{border:1px solid rgba(255,255,255,.06);border-radius:17px;background:#10141c;overflow:hidden}.list>article.opened{border-color:rgba(155,217,255,.2)}.summary{box-sizing:border-box;width:100%;display:flex;align-items:center;justify-content:space-between;padding:16px;border:0;background:transparent;color:#edf7ff;text-align:left}.summary div{display:grid;gap:4px}.summary small{color:#70879b}.summary span{padding:7px 10px;border-radius:12px;background:rgba(255,121,121,.08);color:#ff9c9c;font-size:10px;font-weight:900}.summary span.ok{background:rgba(97,216,165,.09);color:#78e1b4}.drawer{padding:0 16px 16px;border-top:1px solid rgba(255,255,255,.05)}.facts{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;padding:14px 0}.facts span{padding:13px;border-radius:13px;background:#0b1119}.facts small,.facts b{display:block}.facts small{color:#667b8d;font-size:8px}.facts b{margin-top:7px}.columns{display:grid;grid-template-columns:1fr 1fr;gap:8px}.columns>section{padding:13px;border-radius:15px;background:#0b1119}.columns section>header{display:flex;justify-content:space-between;margin-bottom:8px}.columns header span{color:#80c9f4}.columns section>article{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-top:1px solid rgba(255,255,255,.05)}.columns article div{display:grid;gap:3px}.columns article small{color:#667b8d}.columns article em{color:#7890a5;font-size:10px;font-style:normal}.columns article em.paid{color:#78e1b4}.actions{display:flex;flex-wrap:wrap;gap:7px;padding-top:14px}.actions label,.actions button{min-height:39px;border:0;border-radius:11px;padding:0 12px;background:#172535;color:#bde7ff}.actions label{display:flex;align-items:center;gap:8px;color:#8da1b2;font-size:11px}.actions input{width:64px;border:0;background:transparent;color:#fff}.actions button{font-weight:800}.actions button.danger{margin-left:auto;background:rgba(255,100,110,.1);color:#ff9c9c}.notice{padding:11px 14px;border-radius:12px;background:#14283a!important;color:#bde7ff!important}@media(max-width:850px){.facts{grid-template-columns:1fr 1fr}.columns{grid-template-columns:1fr}.summary small{display:block;max-width:65vw;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}</style>
