<script>
  export let data
  $: schemes = data?.remnawave?.connection_schemes || []
</script>
<section class="page"><header><span>МАРШРУТИЗАЦИЯ</span><h2>Схемы подключений</h2><p>Как клиентский трафик проходит через AutoSelect, основные ноды и LTE-резерв.</p></header>
  <div class="flow"><article class="source"><small>КЛИЕНТ</small><b>Happ / ArcVPN</b></article><i>→</i><article class="auto"><small>СХЕМА</small><b>⚡ Автовыбор</b><p>leastLoad · проверка каждые 20 сек.</p></article><i>→</i><div class="destinations">{#each data?.remnawave?.nodes || [] as node}<article class:off={!node.connected}><i></i><span><b>{node.name}</b><small>{node.users_online || 0} онлайн · {node.connected ? 'доступна' : 'отключена'}</small></span></article>{/each}</div></div>
  <div class="cards">{#each schemes as scheme}<article class:auto={scheme.id==='auto'}><header><i></i><div><b>{scheme.name}</b><small>{scheme.kind === 'client_balancer' ? 'Клиентский балансировщик' : 'Резервный маршрут'}</small></div><em>{scheme.active_only_as_fallback ? 'FALLBACK' : 'ACTIVE'}</em></header><dl><div><dt>Интервал пробы</dt><dd>{scheme.probe_interval_seconds || '—'} сек.</dd></div><div><dt>Коэффициент трафика</dt><dd>×{scheme.traffic_factor || 1}</dd></div><div><dt>Распределение</dt><dd>{Object.values(scheme.online_distribution || {}).reduce((a,b)=>a+Number(b),0)} онлайн</dd></div></dl></article>{/each}</div>
</section>
<style>.page{display:grid;gap:22px}header>span{color:#e99772;font-size:10px;font-weight:800;letter-spacing:.14em}h2{margin:8px 0 5px;font-size:30px}header>p{margin:0;color:#8d8687}.flow{display:grid;grid-template-columns:180px 30px 260px 30px 1fr;align-items:center;padding:24px;border:1px solid #302729;border-radius:26px;background:#151214}.flow>i{color:#65595b;text-align:center}.source,.auto{padding:19px;border-radius:20px;background:#211a1c}.auto{background:linear-gradient(135deg,#342326,#20191b);box-shadow:inset 0 0 0 1px #523538}.flow small{color:#817679;font-size:9px;letter-spacing:.1em}.flow b{display:block;margin-top:7px}.flow p{margin:6px 0 0;color:#8d8385;font-size:11px}.destinations{display:grid;grid-template-columns:1fr 1fr;gap:8px}.destinations article{display:flex;align-items:center;gap:9px;padding:13px;border-radius:15px;background:#201a1c}.destinations article>i,.cards header>i{width:8px;height:8px;border-radius:50%;background:#72d5aa}.destinations article.off>i{background:#f08b7d}.destinations span{display:flex;flex-direction:column}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.cards>article{padding:20px;border:1px solid #302729;border-radius:22px;background:#171315}.cards>article.auto{background:linear-gradient(145deg,#2b2022,#171315)}.cards header{display:flex;align-items:center;gap:10px}.cards header div{display:flex;flex:1;flex-direction:column}.cards em{padding:6px 9px;border-radius:10px;background:#2b2426;color:#eba083;font-size:9px;font-style:normal}.cards dl{display:grid;gap:9px;margin:18px 0 0}.cards dl div{display:flex;justify-content:space-between}.cards dt{color:#81787a}.cards dd{margin:0}@media(max-width:1000px){.flow{grid-template-columns:1fr}.flow>i{transform:rotate(90deg)}.cards{grid-template-columns:1fr}.destinations{grid-template-columns:1fr 1fr}}</style>
