<script>
  import ArcIcon from '../../components/ArcIcon.svelte'
  export let data; export let onRefresh; let view='events'
  $: nodes=data?.remnawave?.nodes||[]
  $: incidents=[...nodes.filter(n=>!n.connected).map(n=>({title:`Нода «${n.name}» недоступна`,detail:n.last_status_message||'Нет соединения с RemnaNode',object:n.address})),...(data?.system?.database_integrity!=='ok'?[{title:'Нарушена целостность базы',detail:String(data?.system?.database_integrity||'unknown'),object:'database'}]:[]),...(Number(data?.system?.disk_used_pct||0)>80?[{title:'Заканчивается место на диске',detail:`Использовано ${data.system.disk_used_pct}%`,object:'storage'}]:[])]
  $: services=[['Remnawave',data?.remnawave?.healthy],['Subscription API',data?.operations?.subscription_service],['База ArcVPN',data?.system?.database_integrity==='ok'],['Диск',Number(data?.system?.disk_used_pct||0)<80]]
</script>
<section class="page"><header><div><span>НАБЛЮДАЕМОСТЬ</span><h2>Здоровье системы</h2><p>Аварии, деградации и состояние инфраструктуры.</p></div><button on:click={onRefresh}><ArcIcon name="pulse" size={18}/>Проверить сейчас</button></header><div class:danger={incidents.length} class="score"><b>{incidents.length?Math.max(25,100-incidents.length*18):100}<small>/100</small></b><span><em>{incidents.length?'ТРЕБУЕТСЯ ВНИМАНИЕ':'СИСТЕМА В НОРМЕ'}</em><h3>{incidents.length?`${incidents.length} активных события`:'Критических событий нет'}</h3><p>{nodes.filter(n=>n.connected).length}/{nodes.length} нод подключены</p></span><div><b>{data?.remnawave?.online_users?.length||0}</b><small>пользователей онлайн</small></div></div>
  <nav><button class:active={view==='events'} on:click={()=>view='events'}>События <i>{incidents.length}</i></button><button class:active={view==='nodes'} on:click={()=>view='nodes'}>Ноды</button><button class:active={view==='services'} on:click={()=>view='services'}>Сервисы</button></nav>
  <div class="rows">{#if view==='events'}{#if incidents.length}{#each incidents as item}<article><i></i><span><b>{item.title}</b><p>{item.detail}</p><small>{item.object}</small></span></article>{/each}{:else}<article class="ok"><i></i><span><b>Все проверки пройдены</b><p>Критических событий нет.</p></span></article>{/if}{:else if view==='nodes'}{#each nodes as node}<article class:ok={node.connected}><i></i><span><b>{node.name}</b><p>{node.connected?`${node.users_online||0} онлайн · RAM ${node.memory_used_pct||0}% · ${node.traffic_used_gb||0} ГБ`:'RemnaNode недоступна'}</p><small>{node.address}</small></span></article>{/each}{:else}{#each services as service}<article class:ok={service[1]}><i></i><span><b>{service[0]}</b><p>{service[1]?'Работает штатно':'Требуется проверка'}</p></span></article>{/each}{/if}</div>
</section>
<style>.page{display:grid;gap:18px}.page>header{display:flex;align-items:flex-end;justify-content:space-between}.page>header span,.score em{color:#80c9f4;font-size:10px;font-weight:900;letter-spacing:.15em}.page h2{margin:8px 0 5px;font-size:30px}.page p{margin:0;color:#7890a5}.page>header button{display:flex;gap:8px;padding:12px 16px;border:1px solid rgba(155,217,255,.14);border-radius:14px;background:#14202e;color:#ccecff}.score{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:24px;padding:26px;border:1px solid rgba(155,217,255,.1);border-radius:26px;background:linear-gradient(110deg,#102438,#0a121d 65%)}.score.danger{background:linear-gradient(110deg,#2b1c27,#0a121d 65%)}.score>b{display:grid;width:88px;height:88px;place-content:center;border:7px solid #61d8a5;border-radius:50%;font-size:28px}.score.danger>b{border-color:#ff8f8f}.score>b small{font-size:10px;color:#7890a5}.score h3{margin:7px 0;font-size:22px}.score>div{padding:15px;border-radius:17px;background:#0d1b29}.score>div b,.score>div small{display:block}.score>div b{font-size:25px}.score>div small{color:#7890a5}.page>nav{display:flex;gap:8px;border-bottom:1px solid rgba(155,217,255,.08)}.page>nav button{padding:13px 16px;border:0;border-bottom:2px solid transparent;background:none;color:#7890a5}.page>nav button.active{border-color:#9bd9ff;color:#fff}.page>nav i{padding:3px 7px;border-radius:10px;background:#15314a;color:#9bd9ff;font-style:normal}.rows{display:grid;gap:10px}.rows article{display:flex;align-items:center;gap:14px;padding:18px;border:1px solid rgba(155,217,255,.1);border-radius:19px;background:#0e1926}.rows article>i{width:9px;height:9px;border-radius:50%;background:#ff7979}.rows article.ok>i{background:#61d8a5}.rows span{display:flex;flex-direction:column;gap:5px}.rows small{color:#6f879b}@media(max-width:850px){.score{grid-template-columns:1fr}.page>header{align-items:flex-start}}</style>
