<script>
  import { onMount } from 'svelte'; import { fetchAdminExpenses,createAdminExpense,deleteAdminExpense } from '../../lib/api.js'
  export let data; let report={expenses:[],summary:{}};let title='';let amount='';let category='hosting';let incurred_on=new Date().toISOString().slice(0,10);let recurring=false;let busy=false
  const rub=v=>`${new Intl.NumberFormat('ru-RU').format(Number(v||0))} ₽`
  onMount(load); async function load(){report=await fetchAdminExpenses()}
  async function add(){if(!title||!amount)return;busy=true;try{report=await createAdminExpense({title,amount_rub:Number(amount),category,incurred_on,recurring_monthly:recurring});title='';amount='';recurring=false}finally{busy=false}}
  async function remove(id){if(!confirm('Удалить эту статью расходов?'))return;report=await deleteAdminExpense(id)}
</script>
<section class="page"><header><span>ДЕНЕЖНЫЙ КОНТУР</span><h2>Выручка и расходы</h2><p>Фактические оплаты минус операционные затраты за текущий месяц.</p></header>
  <div class="ledger"><article><small>ВЫРУЧКА</small><b>{rub(report.summary?.month_revenue_rub)}</b></article><article><small>РАСХОДЫ</small><b>{rub(report.summary?.month_expenses_rub)}</b></article><article class:loss={Number(report.summary?.month_net_rub)<0}><small>ЧИСТАЯ ПРИБЫЛЬ</small><b>{rub(report.summary?.month_net_rub)}</b></article></div>
  <form on:submit|preventDefault={add}><input bind:value={title} maxlength="100" placeholder="Например, DHost Германия"/><input bind:value={amount} type="number" min="0.01" step="0.01" placeholder="Сумма, ₽"/><select bind:value={category}><option value="hosting">Хостинг</option><option value="cdn">CDN</option><option value="software">Сервисы</option><option value="marketing">Маркетинг</option><option value="other">Другое</option></select><input bind:value={incurred_on} type="date"/><label><input bind:checked={recurring} type="checkbox"/>Ежемесячно</label><button disabled={busy}>{busy?'Добавляем…':'Добавить расход'}</button></form>
  <div class="list">{#each report.expenses||[] as item}<article><div><b>{item.title}</b><small>{item.incurred_on} · {item.category}{item.recurring_monthly?' · ежемесячно':''}</small></div><strong>{rub(item.amount_rub)}</strong><button on:click={()=>remove(item.id)}>Удалить</button></article>{/each}{#if !(report.expenses||[]).length}<p>Добавьте аренду серверов, CDN и другие затраты — здесь появится реальная прибыль.</p>{/if}</div>
</section>
<style>.page{display:grid;gap:20px;max-width:1120px}.page>header span{color:#80c9f4;font-size:10px;font-weight:900;letter-spacing:.15em}.page h2{margin:8px 0 6px;font-size:30px}.page p{margin:0;color:#7890a5}.ledger{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.ledger article{padding:22px;border:1px solid rgba(155,217,255,.1);border-radius:19px;background:#10141c}.ledger small{color:#6f879b;font-size:9px}.ledger b{display:block;margin-top:14px;font-size:27px}.ledger article:last-child{background:linear-gradient(140deg,rgba(52,146,111,.18),#10141c)}.ledger article.loss{background:linear-gradient(140deg,rgba(190,72,85,.18),#10141c)}form{display:grid;grid-template-columns:2fr 1fr 1fr 1fr auto auto;gap:8px;padding:14px;border:1px solid rgba(255,255,255,.06);border-radius:18px;background:#10141c}form input,form select,form button{min-height:43px;border:0;border-radius:12px;padding:0 12px;background:#0b1119;color:#eaf4fc}form label{display:flex;align-items:center;gap:6px;color:#8da1b2;font-size:11px}form button{background:#9bd9ff;color:#07111d;font-weight:900}.list{display:grid;gap:7px}.list>article{display:grid;grid-template-columns:1fr auto auto;align-items:center;gap:18px;padding:14px 16px;border-radius:15px;background:#10141c}.list article div{display:grid;gap:4px}.list small{color:#6f879b}.list button{border:0;background:transparent;color:#ff9c9c}@media(max-width:900px){.ledger{grid-template-columns:1fr}.page form{grid-template-columns:1fr 1fr}.page form input:first-child{grid-column:1/3}}</style>
