<script>
  import { onMount } from 'svelte'
  import { fetchAdminExpenses, createAdminExpense, deleteAdminExpense } from '../../lib/api.js'
  export let canManage = true
  let report={expenses:[],summary:{}};let title='';let amount='';let category='hosting';let incurred_on=new Date().toISOString().slice(0,10);let recurring=false;let note=''
  let loading=true;let busy=false;let deleting=null;let error='';let notice='';let submitted=false
  const rub=v=>`${new Intl.NumberFormat('ru-RU').format(Number(v||0))} ₽`
  $: amountNumber=Number(amount)
  $: valid=Boolean(title.trim())&&Number.isFinite(amountNumber)&&amountNumber>0&&amountNumber<=100000000&&/^\d{4}-\d{2}-\d{2}$/.test(incurred_on)
  onMount(load)
  async function load({preserveNotice=false}={}){loading=true;error='';if(!preserveNotice)notice='';try{report=await fetchAdminExpenses()}catch(e){error=`Не удалось загрузить расходы: ${e.reason||e.message}`}finally{loading=false}}
  async function add(){submitted=true;if(!canManage||busy||!valid)return;busy=true;error='';notice='';try{report=await createAdminExpense({title:title.trim(),amount_rub:amountNumber,category,incurred_on,recurring_monthly:recurring,note:note.trim()});title='';amount='';note='';recurring=false;submitted=false;notice='Расход добавлен в расчёт текущего месяца.'}catch(e){error=`Не удалось добавить расход: ${e.reason||e.message}`}finally{busy=false}}
  async function remove(item){if(!canManage||deleting!==null||!confirm(`Удалить расход «${item.title}»? Итоги месяца будут пересчитаны.`))return;deleting=item.id;error='';notice='';try{report=await deleteAdminExpense(item.id);notice='Расход удалён, итоги пересчитаны.'}catch(e){error=`Не удалось удалить расход: ${e.reason||e.message}`}finally{deleting=null}}
</script>

<section class="page">
  <header><span>ДЕНЕЖНЫЙ КОНТУР</span><h2>Выручка и расходы</h2><p>Фактические успешные оплаты минус внесённые операционные затраты за текущий месяц.</p></header>
  {#if error}<div class="state error" role="alert"><span>{error}</span><button on:click={()=>load()} disabled={loading}>Повторить</button></div>{/if}
  {#if notice}<p class="notice" role="status">{notice}</p>{/if}
  {#if loading&&!report.expenses.length}<div class="state" role="status">Загружаем финансовую сводку…</div>{/if}
  <div class="ledger" aria-label="Финансовая сводка за текущий месяц"><article><small>ВЫРУЧКА</small><b>{rub(report.summary?.month_revenue_rub)}</b></article><article><small>РАСХОДЫ</small><b>{rub(report.summary?.month_expenses_rub)}</b></article><article class:loss={Number(report.summary?.month_net_rub)<0}><small>ЧИСТАЯ ПРИБЫЛЬ</small><b>{rub(report.summary?.month_net_rub)}</b></article></div>
  <form on:submit|preventDefault={add} aria-label="Новый расход">
    <label><span>Название</span><input bind:value={title} maxlength="100" required placeholder="Например, аренда узла" aria-invalid={submitted&&!title.trim()}/></label>
    <label><span>Сумма, ₽</span><input bind:value={amount} type="number" min="0.01" max="100000000" step="0.01" required placeholder="0,00" aria-invalid={submitted&&!(amountNumber>0)}/></label>
    <label><span>Категория</span><select bind:value={category}><option value="hosting">Хостинг</option><option value="cdn">CDN</option><option value="software">Сервисы</option><option value="marketing">Маркетинг</option><option value="other">Другое</option></select></label>
    <label><span>Дата</span><input bind:value={incurred_on} type="date" required/></label>
    <label class="note"><span>Комментарий</span><input bind:value={note} maxlength="500" placeholder="Необязательно"/></label>
    <label class="check"><input bind:checked={recurring} type="checkbox"/>Ежемесячный расход</label>
    <button disabled={busy||!canManage}>{busy?'Добавляем…':'Добавить расход'}</button>
    {#if submitted&&!valid}<small class="validation" role="alert">Заполните название, положительную сумму и дату.</small>{/if}
  </form>
  <div class="list" aria-busy={loading}>{#each report.expenses||[] as item}<article><div><b>{item.title}</b><small>{item.incurred_on} · {item.category}{item.recurring_monthly?' · ежемесячно':''}</small>{#if item.note}<p>{item.note}</p>{/if}</div><strong>{rub(item.amount_rub)}</strong><button disabled={deleting!==null||!canManage} aria-label={`Удалить расход ${item.title}`} on:click={()=>remove(item)}>{deleting===item.id?'Удаляем…':'Удалить'}</button></article>{/each}{#if !loading&&!error&&!(report.expenses||[]).length}<p class="empty">Расходов пока нет. Добавьте подтверждённые операционные затраты, чтобы рассчитать чистую прибыль.</p>{/if}</div>
</section>

<style>
.page{display:grid;gap:20px;max-width:1120px;min-width:0}.page>header span{color:#80c9f4;font-size:10px;font-weight:900;letter-spacing:.15em}.page h2{margin:8px 0 6px;font-size:30px}.page p{margin:0;color:#7890a5}.ledger{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.ledger article{padding:22px;border:1px solid rgba(155,217,255,.1);border-radius:19px;background:#10141c}.ledger small{color:#6f879b;font-size:9px}.ledger b{display:block;margin-top:14px;font-size:27px}.ledger article:last-child{background:linear-gradient(140deg,rgba(52,146,111,.18),#10141c)}.ledger article.loss{background:linear-gradient(140deg,rgba(190,72,85,.18),#10141c)}form{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:10px;padding:14px;border:1px solid rgba(255,255,255,.06);border-radius:18px;background:#10141c}form label{display:grid;gap:6px;min-width:0;color:#8da1b2;font-size:10px}form label>span{font-weight:800;letter-spacing:.04em}form input,form select,form button{box-sizing:border-box;width:100%;min-height:43px;border:0;border-radius:12px;padding:0 12px;background:#0b1119;color:#eaf4fc}form .note{grid-column:1/4}form .check{display:flex;align-items:center;flex-direction:row;gap:8px;padding-top:17px;font-size:11px}form .check input{width:18px;min-height:18px}form button{grid-column:4;background:#9bd9ff;color:#07111d;font-weight:900}.validation{grid-column:1/-1;color:#ffb1b6}.list{display:grid;gap:7px}.list>article{display:grid;grid-template-columns:minmax(0,1fr) auto auto;align-items:center;gap:18px;padding:14px 16px;border-radius:15px;background:#10141c}.list article div{display:grid;gap:4px;min-width:0}.list small{color:#6f879b}.list article p{overflow-wrap:anywhere;font-size:11px}.list button,.state button{border:0;background:transparent;color:#ff9c9c}.state,.notice,.empty{padding:14px;border-radius:13px;background:#14283a;color:#bde7ff}.state{display:flex;align-items:center;justify-content:space-between;gap:12px}.state button{min-height:36px;border-radius:10px;padding:0 12px;background:#223d55;color:#dff3ff}.state.error{background:rgba(150,54,65,.15);color:#ffb1b6}button:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid #9bd9ff;outline-offset:2px}button:disabled{cursor:not-allowed;opacity:.5}@media(max-width:900px){.ledger{grid-template-columns:1fr}.page form{grid-template-columns:1fr 1fr}.page form .note{grid-column:1/-1}.page form .check{grid-column:1}.page form>button{grid-column:2}}@media(max-width:520px){.page h2{font-size:25px}.page form{grid-template-columns:1fr}.page form label,.page form .note,.page form .check,.page form>button{grid-column:1}.page form .check{padding-top:2px}.list>article{grid-template-columns:minmax(0,1fr) auto;gap:10px}.list>article>button{grid-column:1/-1;justify-self:start;min-height:38px}.ledger b{font-size:23px}}
</style>
