import {lazy,Suspense,type ReactNode} from 'react';
import {StatCard} from '@/components/stats/StatCard';
import {ChartBarIcon,CheckCircleIcon,CreditCardIcon,UsersIcon,WalletIcon,SearchIcon} from '@/components/icons';
import {money,stamp,labels,type Report,type Filters} from './ArcPartnerCabinet';
const Chart=lazy(()=>import('@/components/sales-stats/SimpleAreaChart').then(m=>({default:m.SimpleAreaChart})));
function Badge({children,success=false}:{children:ReactNode;success?:boolean}) {return <span className={`inline-block rounded-full px-2.5 py-1 text-xs font-medium ${success?'bg-success-500/20 text-success-400':'bg-accent-500/20 text-accent-300'}`}>{children}</span>;}
function Table({columns,children,count,empty}:{columns:string[];children:ReactNode;count:number;empty:string}) {
 return <section className="overflow-hidden rounded-2xl border border-dark-700/50 bg-dark-900/30 backdrop-blur-xl">{count?<div className="overflow-x-auto" tabIndex={0} aria-label="Таблица статистики"><table className="w-full text-left text-sm [&_th]:px-5 [&_th]:py-4 [&_th]:font-medium [&_th]:text-dark-400 [&_td]:px-5 [&_td]:py-5 [&_td]:border-t [&_td]:border-dark-700/50 [&_td]:align-top"><thead><tr>{columns.map(c=><th scope="col" key={c}>{c}</th>)}</tr></thead><tbody>{children}</tbody></table></div>:<div className="flex min-h-64 flex-col items-center justify-center gap-5 py-16 text-dark-400"><div className="rounded-2xl bg-dark-800 p-5"><CheckCircleIcon className="h-8 w-8"/></div><p role="status">{empty}</p></div>}</section>;
}
function daily(data:Report,filters:Filters) {
 const rows=new Map((data.series||[]).map(r=>[r.day,{...r,clients:0}]));
 for(const row of data.client_series||[]) rows.set(row.day,{day:row.day,purchases:0,revenue_cents:0,reward_cents:0,...rows.get(row.day),clients:row.clients});
 const from=filters.from||Array.from(rows.keys()).sort()[0];const to=filters.to||new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow'}).format(new Date());
 if(!from)return [{day:to,clients:0,purchases:0,revenue_cents:0,reward_cents:0}];
 const result=[];let date=new Date(from+'T12:00:00Z');const end=new Date(to+'T12:00:00Z');
 for(let i=0;date<=end&&i<3660;i++,date.setUTCDate(date.getUTCDate()+1)){const day=date.toISOString().slice(0,10);result.push(rows.get(day)||{day,clients:0,purchases:0,revenue_cents:0,reward_cents:0});}return result;
}
export function PartnerContent({screen,data,filters,onFilter}:{screen:'statistics'|'purchases'|'clients'|'payouts';data:Report;filters:Filters;onFilter:(filters:Filters)=>void}) {
 if(screen==='statistics') {const series=daily(data,filters);return <>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Привлечено клиентов" value={data.stats.clients} icon={<UsersIcon/>}/><StatCard label="Активные триалы" value={data.stats.trials||0} icon={<UsersIcon/>}/><StatCard label="Активные платные" value={data.stats.paid||0} tone="success" icon={<CheckCircleIcon/>}/><StatCard label="Конверсия в оплату" value={data.stats.conversion_percent+'%'} icon={<ChartBarIcon/>}/></div>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Покупки" value={data.stats.purchases} icon={<CreditCardIcon/>}/><StatCard label="Продления" value={data.stats.renewals}/><StatCard label="Оплачено клиентами" value={money(data.stats.revenue_cents)}/><StatCard label="Ваш доход за период" value={money(data.stats.reward_cents)} tone="success" icon={<WalletIcon/>}/></div>
  <div className="grid gap-4 lg:grid-cols-2"><Suspense fallback={<p>Загружаем графики…</p>}><Chart title="Привлечённые клиенты по дням" valueLabel="Клиенты" chartId="partner-clients" data={series.map(r=>({date:r.day,value:r.clients}))}/><Chart title="Покупки и продления по дням" valueLabel="Покупки" chartId="partner-purchases" data={series.map(r=>({date:r.day,value:r.purchases}))}/><Chart title="Ваш доход по дням, ₽" valueLabel="Доход" chartId="partner-rewards" data={series.map(r=>({date:r.day,value:r.reward_cents/100}))}/></Suspense><div className="rounded-2xl border border-dark-700/50 bg-dark-800/30 p-5"><h2 className="font-semibold">Клиенты и покупки</h2><dl className="mt-5 space-y-4 text-sm">{[['Оплатили из привлечённых',data.stats.cohort_paying_clients],['Средний чек',money(data.stats.avg_purchase_cents)],['Повторные покупатели',data.stats.repeat_clients],['Подписка истекла',data.stats.expired||0],['Без подписки',data.stats.without_subscription||0]].map(([key,value])=><div className="flex justify-between gap-4" key={key}><dt className="text-dark-400">{key}</dt><dd className="font-semibold">{value}</dd></div>)}</dl><p className="mt-5 text-xs leading-5 text-dark-500">Конверсия показывает долю привлечённых за период клиентов с подтверждённой покупкой. Пробный период за 10 ₽ не даёт партнёрского дохода. Триалы и платные — активные подписки этой группы клиентов.</p></div></div>
 </>;}
 if(screen==='purchases')return <>
  <div className="relative"><SearchIcon className="pointer-events-none absolute left-3 top-3 h-5 w-5 text-dark-500"/><input aria-label="Поиск клиента" placeholder="Поиск по обезличенному клиенту…" value={filters.search} onChange={e=>onFilter({...filters,search:e.target.value})} className="w-full rounded-xl border border-dark-700 bg-dark-800 py-3 pl-10 pr-4 text-sm outline-none focus:ring-1 focus:ring-accent-500"/></div>
  <div className="flex flex-wrap gap-2" aria-label="Вид покупки">{[['','Все покупки'],['new','Подписки'],['renew','Продления'],['addon_device','Устройства'],['addon_lte','Трафик'],['addon_combined','Устройства и трафик'],['upgrade','Смена тарифа']].map(([value,label])=><button aria-pressed={filters.kind===value} key={value} onClick={()=>onFilter({...filters,kind:value})} className={`rounded-lg px-3 py-2 text-sm ${filters.kind===value?'bg-accent-500 text-on-accent':'bg-dark-800 text-dark-300'}`}>{label}</button>)}</div>
  <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 [&>*:last-child]:col-span-2 sm:[&>*:last-child]:col-span-1"><StatCard label="Покупки" value={data.stats.purchases} icon={<CreditCardIcon/>}/><StatCard label="Оплачено" value={money(data.stats.revenue_cents)} icon={<CheckCircleIcon/>}/><StatCard label="Ваш доход" value={money(data.stats.reward_cents)} tone="success" icon={<WalletIcon/>}/></div>
  <Table columns={['Что купили','Клиент','Оплачено','Ставка','Ваш доход','Дата']} count={data.purchases.length} empty="Покупки не найдены">{data.purchases.map(row=><tr key={row.id}><td className="min-w-48"><Badge>{row.purchase_description||labels[row.purchase_kind]}</Badge><div className="mt-2 text-xs text-dark-500">{labels[row.purchase_kind]}</div></td><td className="whitespace-nowrap text-dark-400">{row.client}</td><td className="whitespace-nowrap text-base font-bold">{money(row.purchase_cents)}</td><td>{row.rate_bps/100}%</td><td className="whitespace-nowrap text-base font-semibold text-success-400">{money(row.amount_cents)}</td><td className="whitespace-nowrap text-xs text-dark-400">{stamp(row.purchase_at)}</td></tr>)}</Table>
 </>;
 if(screen==='payouts')return <>
  <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 [&>*:last-child]:col-span-2 sm:[&>*:last-child]:col-span-1"><StatCard label="К выплате сейчас" value={money(data.balance.available)} tone="success" icon={<WalletIcon/>}/><StatCard label="Выплачено за всё время" value={money(data.balance.paid)} icon={<CheckCircleIcon/>}/><StatCard label="Выплаты за период" value={data.payout_stats?.count ?? data.payouts.filter(p=>p.kind==='payout').length} icon={<CreditCardIcon/>}/></div>
  <Table columns={['Сумма','Статус','Способ','Дата','Примечание']} count={data.payouts.length} empty="Выплат за этот период нет">{data.payouts.map(row=><tr key={row.id}><td className="whitespace-nowrap text-base font-bold">{money(Math.abs(row.amount_cents))}</td><td><Badge success={row.kind==='payout'}>{row.kind==='reversal'?'Отмена выплаты':'Выплачено'}</Badge></td><td className="text-dark-400">{row.method||'—'}</td><td className="whitespace-nowrap text-xs text-dark-400">{stamp(row.occurred_at)}</td><td className="min-w-40 break-words text-dark-400">{row.note||'—'}</td></tr>)}</Table><p className="text-xs text-dark-500">Владелец переводит деньги вручную. Отмены сохраняются в истории.</p>
 </>;
 return <Table columns={['Клиент','Привлечён','Ссылка','Ставка','Покупки']} count={data.clients.length} empty="Клиенты не найдены">{data.clients.map(row=><tr key={row.client}><td>{row.client}</td><td className="whitespace-nowrap text-xs text-dark-400">{stamp(row.bound_at)}</td><td><Badge>{row.source_name}</Badge></td><td>{row.rate_bps/100}%</td><td>{row.purchases}</td></tr>)}</Table>;
}
