import {useEffect,useState} from 'react';
type Profile={source_name:string;display_name:string;enabled:boolean;include_in_auto:boolean;protocol_label:string;sort_order:number};
export default function ArcSubscriptionCatalog(){
 const [profiles,setProfiles]=useState<Profile[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [preview,setPreview]=useState(false);
 useEffect(()=>{fetch('/api/admin/subscription-catalog',{credentials:'include'}).then(async r=>{if(!r.ok)throw new Error();setProfiles((await r.json()).profiles);}).catch(()=>setMessage('Не удалось загрузить структуру подписки.'));},[]);
 const visible=profiles.filter(p=>!/(Германия|Канада|Франция|Албания)/.test(p.source_name)&&!p.protocol_label.includes('Hysteria')&&!/(Обход|LTE|Лучший)/.test(p.source_name));
 const update=(source:string,patch:Partial<Profile>)=>{setProfiles(profiles.map(p=>p.source_name===source?{...p,...patch}:p));setPreview(false);};
 const move=(source:string,direction:number)=>{const visibleIndex=visible.findIndex(p=>p.source_name===source);const neighbor=visible[visibleIndex+direction];if(!neighbor)return;const index=profiles.findIndex(p=>p.source_name===source);const target=profiles.findIndex(p=>p.source_name===neighbor.source_name);const next=[...profiles];[next[index],next[target]]=[next[target],next[index]];setProfiles(next);setPreview(false);};
 const save=async()=>{setBusy(true);try{const r=await fetch('/api/admin/subscription-catalog',{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({profiles})});if(!r.ok)throw new Error();setProfiles((await r.json()).profiles);setMessage('Структура опубликована. Клиентам нужно обновить подписку.');setPreview(false);}catch{setMessage('Не удалось сохранить структуру.');}finally{setBusy(false);}};
 return <section className="mt-8 space-y-3"><h2 className="text-xl font-semibold">Локации в подписке</h2><p className="text-sm text-dark-400">Названия, порядок и выдача существующих профилей. Новые серверы здесь не создаются. Балансировщики редактируются выше.</p>{visible.map(p=><article key={p.source_name} className="rounded-xl border border-dark-700 p-4"><div className="flex flex-wrap items-center gap-3"><label className="flex-1 text-xs text-dark-400">{p.source_name}<input value={p.display_name} maxLength={120} onChange={e=>update(p.source_name,{display_name:e.target.value})} className="mt-1 w-full rounded-lg bg-dark-900 p-2 text-sm text-dark-100"/></label><button aria-label={`Поднять ${p.display_name}`} onClick={()=>move(p.source_name,-1)}>↑</button><button aria-label={`Опустить ${p.display_name}`} onClick={()=>move(p.source_name,1)}>↓</button></div><div className="mt-3 flex flex-wrap gap-4 text-sm"><label><input type="checkbox" checked={p.enabled} onChange={e=>update(p.source_name,{enabled:e.target.checked})}/> Выдавать в подписке</label>{['Польша','Нидерланды','Швеция'].includes(p.source_name)?<span className="text-dark-400">Алиас: не добавляет вес в автовыборе</span>:<label><input type="checkbox" checked={p.include_in_auto} onChange={e=>update(p.source_name,{include_in_auto:e.target.checked})}/> Участвует в автовыборе</label>}<span className="text-dark-400">{p.protocol_label}</span></div></article>)}{profiles.length>0&&<button onClick={()=>setPreview(true)} className="rounded-xl border border-primary-500/40 px-4 py-2">Предпросмотр структуры</button>}{preview&&<div className="rounded-xl border border-dark-700 p-4"><ol className="space-y-1">{visible.filter(p=>p.enabled).map((p,i)=><li key={p.source_name}>{i+1}. {p.display_name}{p.include_in_auto?' · автовыбор':''}</li>)}</ol><button disabled={busy} onClick={save} className="mt-4 rounded-xl bg-primary-500/20 px-4 py-2 text-primary-300">Опубликовать структуру</button></div>}{message&&<p role="status" className="text-sm text-primary-300">{message}</p>}</section>;
}
