#!/usr/bin/env python3
"""Idempotent Estonia Remnawave node preparation.

Creates a dedicated two-inbound profile, a disabled-delivery node record and two
disabled Hosts. Secrets are generated by Remnawave/OpenSSL and never printed.
Promotion is intentionally a separate manual gate after node and tunnel checks.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from bot.services.panels.remnawave import RemnawaveClient
from bot.services.remnawave_stats import remnawave_authority_config


PROFILE_NAME = "ArcVPN Estonia 1chost"
NODE_NAME = "ArcVPN Estonia 1chost"
DOMAIN = "ee.arccnet.space"
NODE_ADDRESS = "95.85.249.187"
NODE_PORT = 22500
TCP_TAG = "EE_1CHOST_VLESS_TCP"
HY2_TAG = "EE_1CHOST_HYSTERIA2"
STATE_PATH = Path(".secrets/estonia-remnawave-state.json")


async def request(client: RemnawaveClient, method: str, path: str, **kwargs):
    return await client._request(method, path, **kwargs)


async def prepare(apply: bool, certificate_fingerprint: str) -> dict:
    client = RemnawaveClient(remnawave_authority_config())
    try:
        profiles_payload = await request(client, "GET", "/api/config-profiles")
        profiles = profiles_payload.get("configProfiles", [])
        existing = next((item for item in profiles if item.get("name") == PROFILE_NAME), None)
        nodes = await request(client, "GET", "/api/nodes")
        node = next((item for item in nodes if item.get("name") == NODE_NAME), None)
        if not apply:
            return {
                "apply": False,
                "profile_exists": bool(existing),
                "node_exists": bool(node),
                "domain": DOMAIN,
                "node_port": NODE_PORT,
            }
        if existing or node:
            raise RuntimeError("Estonia profile/node already exists; inspect before retry")

        keypair = await request(client, "GET", "/api/system/tools/x25519/generate")
        private_key = keypair["keypairs"][0]["privateKey"]
        short_id = subprocess.check_output(["openssl", "rand", "-hex", "8"], text=True).strip()
        fingerprint = certificate_fingerprint.strip().upper()
        if len(fingerprint.split(":")) != 32:
            raise RuntimeError("A SHA-256 certificate fingerprint is required")
        config = {
            "log": {"loglevel": "none"},
            "dns": {"servers": ["1.1.1.1", "1.0.0.1"]},
            "inbounds": [
                {
                    "tag": TCP_TAG, "port": 443, "listen": "0.0.0.0", "protocol": "vless",
                    "settings": {"clients": [], "decryption": "none"},
                    "sniffing": {"enabled": True, "destOverride": ["http", "tls", "quic"]},
                    "streamSettings": {
                        "network": "raw", "security": "reality",
                        "realitySettings": {
                            "target": "google.com:443", "shortIds": [short_id],
                            "privateKey": private_key,
                            "serverNames": ["google.com", "www.google.com"],
                        },
                    },
                },
                {
                    "tag": HY2_TAG, "port": 443, "listen": "0.0.0.0", "protocol": "hysteria",
                    "settings": {"clients": [], "version": 2},
                    "streamSettings": {
                        "network": "hysteria", "security": "tls",
                        "finalmask": {"quicParams": {"debug": False, "congestion": "bbr"}},
                        "tlsSettings": {
                            "alpn": ["h3"],
                            "certificates": [{
                                "certificateFile": "/var/lib/remnawave/configs/xray/ssl/cert.pem",
                                "keyFile": "/var/lib/remnawave/configs/xray/ssl/cert.key",
                            }],
                        },
                        "hysteriaSettings": {"version": 2},
                    },
                },
            ],
            "outbounds": [
                {"tag": "DIRECT", "protocol": "freedom"},
                {"tag": "BLOCK", "protocol": "blackhole"},
            ],
            "routing": {"rules": [
                {"ip": ["geoip:private"], "type": "field", "outboundTag": "BLOCK"},
                {"type": "field", "domain": ["geosite:private"], "outboundTag": "BLOCK"},
                {"type": "field", "protocol": ["bittorrent"], "outboundTag": "BLOCK"},
            ]},
        }
        profile = await request(
            client, "POST", "/api/config-profiles",
            json={"name": PROFILE_NAME, "config": config},
        )
        inbound_ids = {item["tag"]: item["uuid"] for item in profile["inbounds"]}
        node = await request(client, "POST", "/api/nodes", json={
            "name": NODE_NAME,
            "address": NODE_ADDRESS,
            "port": NODE_PORT,
            "configProfile": {
                "activeConfigProfileUuid": profile["uuid"],
                "activeInbounds": [inbound_ids[TCP_TAG], inbound_ids[HY2_TAG]],
            },
            "isTrafficTrackingActive": False,
            "trafficLimitBytes": 0,
            "notifyPercent": 0,
            "trafficResetDay": 1,
            "excludedInbounds": [],
            "countryCode": "EE",
            "consumptionMultiplier": 1.0,
        })

        host_base = {
            "address": DOMAIN, "port": 443, "path": "", "host": "",
            "fingerprint": "firefox", "allowInsecure": False,
            "isDisabled": True, "isHidden": False, "nodes": [node["uuid"]],
        }
        tcp_host = await request(client, "POST", "/api/hosts", json={
            **host_base,
            "inbound": {
                "configProfileUuid": profile["uuid"],
                "configProfileInboundUuid": inbound_ids[TCP_TAG],
            },
            "remark": "Эстония #1", "sni": "google.com", "alpn": None,
            "securityLayer": "DEFAULT",
        })
        hy2_host = await request(client, "POST", "/api/hosts", json={
            **host_base,
            "inbound": {
                "configProfileUuid": profile["uuid"],
                "configProfileInboundUuid": inbound_ids[HY2_TAG],
            },
            "remark": "Эстония #2", "sni": DOMAIN, "alpn": "h3",
            "securityLayer": "TLS", "pinnedPeerCertSha256": fingerprint,
            "verifyPeerCertByName": DOMAIN,
        })
        state = {
            "profile_uuid": profile["uuid"], "node_uuid": node["uuid"],
            "tcp_inbound_uuid": inbound_ids[TCP_TAG], "hy2_inbound_uuid": inbound_ids[HY2_TAG],
            "tcp_host_uuid": tcp_host["uuid"], "hy2_host_uuid": hy2_host["uuid"],
            "certificate_fingerprint": fingerprint,
        }
        STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        STATE_PATH.write_text(json.dumps(state, indent=2), encoding="utf-8")
        STATE_PATH.chmod(0o600)
        return {"apply": True, "prepared": True, "hosts_disabled": True}
    finally:
        await client.close()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--certificate-fingerprint", default="")
    args = parser.parse_args()
    print(json.dumps(asyncio.run(prepare(args.apply, args.certificate_fingerprint)), ensure_ascii=False))


if __name__ == "__main__":
    main()
